import Layout from "@/layout/Layout";
import "./globals.css";
import { yekan } from "@/utils/fonts";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextTopLoader
          color="#f59e0b"
          height={3}
          showSpinner={false}
        />
        <NextAuthProvider>
          <Layout>{children}</Layout>
          <Toaster position="top-center" />
        </NextAuthProvider>
      </body>
    </html>
  );
}